apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: details-${version}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: details
        version: ${version}
    spec:
      containers:
      - name: details
        image: bevyx/demo-bookinfo-details:${version}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080